### ISSUE TITLE
前端加载后端roms显示空白

### ISSUE THREAD

**Issue by chspan** [taiyuuki/nes-web#2]
错误显示加载数据失败，curl后端数据是客户获取到
[root@test roms]# curl -l http://localhost:8848/suggestions?keyword=11
{"code":200,"suggestions":[{"id":503,"value":"轰炸超人 (v20100411) (繁)","cover":"http://localhost:8848/roms/img/503a.png"roms/img/587a.png"},{"id":592,"value":"玛利欧兄弟 (v20110401) (繁)","cover":"http://localhost:8848/roms/img/592a.png"},{"i/roms/img/593a.png"},{"id":594,"value":"玛利欧兄弟拆屋工 (v20110409) (繁)","cover":"http://localhost:8848/roms/img/594a.pn8848/roms/img/664a.png"},{"id":899,"value":"阿尔戈斯战士 (v1.11) (简)","cover":"http://localhost:8848/roms/img/899a.png"}]
![image](https://github.com/taiyuuki/nes-web/assets/19632399/2ea8f89a-272c-4bcb-9976-1e66d86647cc)
![image](https://github.com/taiyuuki/nes-web/assets/19632399/08dcb75d-97d4-40c6-a67c-b8a4e959ec35)
![image](https://github.com/taiyuuki/nes-web/assets/19632399/703debe7-b275-4b11-be91-47d2975328d0)

**Comment by taiyuuki** [comment]
需要设置一下server.config.ts和client.config.ts中的baseURL。

**Comment by chspan** [comment]
/server/src/server.config.ts

**Comment by chspan** [comment]
/client/src/client.config.ts   /server/src/server.config.ts  感谢

**Comment by chspan** [comment]
请问我新增nes游戏，类型怎么修改呢  是要改数据库吗 
![image](https://github.com/taiyuuki/nes-web/assets/19632399/f567bdb1-69e5-469f-a5f7-242995573711)

**Comment by taiyuuki** [comment]
> 请问我新增nes游戏，类型怎么修改呢 是要改数据库吗 ![image](https://private-user-images.githubusercontent.com/19632399/286547549-f567bdb1-69e5-469f-a5f7-242995573711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNTEyNjMsIm5iZiI6MTcwMTI1MDk2MywicGF0aCI6Ii8xOTYzMjM5OS8yODY1NDc1NDktZjU2N2JkYjEtNjllNS00NjlmLWE1ZjctMjQyOTk1NTczNzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA5NDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZjU3YjQ2ZGM3ZTViMTk1YzVmMTU2ODY4ZWNkOWUzODU3YzViN2NiNjI0NGM2OTAxODdkZGVlYTVjOGQ1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q2uvDP8bb2lGf3Yk6eJlmFA8jMGPLuPdUTn12DBBoWI)

是的，我没有做增删功能，只能手动修改数据库。

**Comment by chspan** [comment]
server/db/nes.sqlite3 请问修改这个吧，是否有那些需要注意呢

**Comment by taiyuuki** [comment]
> server/db/nes.sqlite3 请问修改这个吧，是否有那些需要注意呢

就是这个，不知道你是想怎么改？其实里面总共就三张表，categorys（这单词严格来说应该写作categories，但我懒得改了）、banner、roms，分别对应游戏分类、轮播图、游戏ROM的数据。

**Comment by chspan** [comment]
> > server/db/nes.sqlite3 请问修改这个吧，是否有那些需要注意呢
> 
> 就是这个，不知道你是想怎么改？其实里面总共就三张表，categorys（这单词严格来说应该写作categories，但我懒得改了）、banner、roms，分别对应游戏分类、轮播图、游戏ROM的数据。

**Comment by chspan** [comment]
您好，以后会加rom街机模拟器web版吗

**Comment by chspan** [comment]
![image](https://github.com/taiyuuki/nes-web/assets/19632399/eb3e0d63-58b6-44a7-a1e1-dd0ff1d92d74)
你好这种是缓存吗，还是只能改数据库呢， 文件是存在的

**Comment by taiyuuki** [comment]
> ![image](https://private-user-images.githubusercontent.com/19632399/286842611-eb3e0d63-58b6-44a7-a1e1-dd0ff1d92d74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjg1MDEsIm5iZiI6MTcwMTMyODIwMSwicGF0aCI6Ii8xOTYzMjM5OS8yODY4NDI2MTEtZWIzZTBkNjMtNThiNi00NGE3LWExZTEtZGQwZmYxZDkyZDc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3MTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NmQ0MmY5YzM5NmU3ZjBjMzYzOTRkMjA5YTY4NGJjMzFmMzFjYzc5YTgxYWEzZThlZTc5NmVlNWM3YmY1NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4qSPZjJFUqF4Z4MAXqzRnpcQRXJVbZa47ihHe63bPhc)
> 你好这种是缓存吗，还是只能改数据库呢， 文件是存在的

这是浏览器里的缓存，清一下就行了。
